FROM node:alpine
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
RUN chmod +x node_modules/.bin/* && \
    find node_modules -name "*.js" -exec chmod +x {} \; 2>/dev/null || true
COPY . .
CMD ["npm", "run", "start"]
