services:
  client:
    build: ./client
    
  server:
    build: ./server
    
  worker:
    build: ./worker
    
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server
