name: multi-docker 

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build development image
      run: docker build -t mhj/react-test -f ./client/Dockerfile.dev ./client

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build production images
      run: |
        docker build -t mhj/multi-client ./client
        docker build -t mhj/multi-nginx ./nginx
        docker build -t mhj/multi-server ./server
        docker build -t mhj/multi-worker ./worker

    - name: Login to Aliyun Container Registry
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_ID }} crpi-pj4m4jq6uloanq7g.cn-beijing.personal.cr.aliyuncs.com --password-stdin
    
    - name: Push images to registry
      run: |
        docker push mhj/multi-client
        docker push mhj/multi-server
        docker push mhj/multi-worker
        docker push mhj/multi-nginx
